version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password

